name: Deploy Hugo site to Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Go is required for Hugo Modules
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # Install the latest extended Hugo (avoid 404 on missing versions)
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # Node for PostCSS/js.Build; install deps declared by your Hugo modules
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm packages from Hugo modules
        run: |
          hugo mod npm pack
          npm ci

      # Ensure theme modules are present (and vendor for reproducibility)
      - name: Fetch and vendor Hugo modules
        run: |
          hugo mod get -u
          hugo mod vendor

      # Build with the correct baseURL for your project page
      - name: Build site
        run: |
          hugo --minify --baseURL "https://vikrant-bhati.github.io/profile/"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
