# .github/workflows/deploy.yml
name: Deploy Hugo site to Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.20' }
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.128.1'
          extended: true
      - name: Build
        run: hugo --minify --baseURL "https://vikrant-bhati.github.io/profile/"
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
